"""Added fulltext column to Post

Revision ID: 2af61ed1cded
Revises: fd3be998172a
Create Date: 2023-07-09 22:12:04.380503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af61ed1cded'
down_revision = 'fd3be998172a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('fulltext', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'fulltext')
    # ### end Alembic commands ###
